language: node_js
node_js:
  - "12"

cache:
  yarn: true
  directories:
    - coverage

before_script:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    - stage: coveralls
      script: yarn coveralls
    #- stage: deploy
    #  script: yarn publish
    #  if: branch = master
