language: node_js
node_js:
  - "12"

cache:
  yarn: true

before_script:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: test
      script: yarn test
    #- stage: deploy
    #  script: yarn publish
    #  if: branch = master
