trigger:
  - master
  - dev
  - feat/*

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: Install Node 12

  # Install dependencies
  - script: yarn install
    displayName: Install deps

  # Test runner
  - script: yarn test
    displayName: Run unit tests

  # Build library
  - script: yarn build
    displayName: Build library

  # Package library for release
  - script: yarn pack
    displayName: Package library for release
    condition: and(succeeded(), 'master')

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)/lib'
      contents: 'lib/**/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)/lib'
    displayName: 'Copy dist output'
    condition: and(succeeded(), 'master')

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/lib'
      artifactName: lib
    displayName: 'Publish lib files as artifacts'
    condition: and(succeeded(), 'master')

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.tgz'
      targetFolder: '$(Build.ArtifactStagingDirectory)/npm'
    displayName: Copy npm package
    condition: and(succeeded(), 'master')

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'package.json'
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: 'Copy package.json'
    condition: and(succeeded(), 'master')

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
      artifactName: npm
    displayName: 'Publish npm artifact'
    condition: and(succeeded(), 'master')

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: ReleaseNotes.MD
      targetFolder: '$(Build.ArtifactStagingDirectory)/release-notes'
    displayName: Copy Release Notes
    condition: and(succeeded(), 'master')

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/release-notes'
      artifactName: release-notes
    displayName: Publish Release Notes artifact
    condition: and(succeeded(), 'master')
